[package]
name    = "shiden"
version = "0.1.0"
edition = "2024"

[dependencies]
exstreamer = { git = "https://github.com/jasonshyang/exstreamer" }
mizuhiki-ta = { git = "https://github.com/jasonshyang/mizuhiki-ta" }

anyhow = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
futures = "0.3"